### ISSUE TITLE
The GB18030 locale is broken

### ISSUE THREAD

**Issue by bhaible** [CTSRD-CHERI/cheribsd#1971]
The gnulib unit test `tests/test-wcrtomb.sh` fails on CheriBSD, while it succeeds on FreeBSD 14.0.

```
$ LC_ALL=zh_CN.GB18030 ./test-wcrtomb 5
In-address space security exception (core dumped)
```
In gdb, I get this stack trace:
```
(gdb) where
#0  strlen (str=0xfffffff7fcfc [rwRW,0xfffffff7fcfc-0xfffffff7fcfd] "\t")
    at /local/scratch/jenkins/workspace/CheriBSD-pipeline_releng_22.12@2/cheribsd/lib/libc/string/strlen.c:146
#1  0x0000000040268790 in _GB18030_mbrtowc (
    pwc=0xfffffff7fcf8 [rwRW,0xfffffff7fcf8-0xfffffff7fcfc] L"", 
    s=0xfffffff7fcfc [rwRW,0xfffffff7fcfc-0xfffffff7fcfd] "\t", n=1, 
    ps=0xfffffff7fd00 [rwRW,0xfffffff7fd00-0xfffffff7fd80])
    at /local/scratch/jenkins/workspace/CheriBSD-pipeline_releng_22.12@2/cheribsd/lib/libc/locale/gb18030.c:127
#2  0x00000000402670a4 in btowc_l (l=<optimized out>, c=<optimized out>)
    at /local/scratch/jenkins/workspace/CheriBSD-pipeline_releng_22.12@2/cheribsd/lib/libc/locale/btowc.c:58
#3  btowc (c=<optimized out>)
    at /local/scratch/jenkins/workspace/CheriBSD-pipeline_releng_22.12@2/cheribsd/lib/libc/locale/btowc.c:65
#4  0x0000000000111540 in main (argc=2, 
    argv=0xffffbff7f620 [rwRW,0xffffbff7f620-0xffffbff7f650])
    at ../../gltests/test-wcrtomb.c:101
```

In `lib/libc/locale/gb18030.c` line 125 or 127, it is wrong to call `strlen(s)`, because `s` cannot be assumed to be NUL-terminated here. The function must only access `s[0], ..., s[n-1]` and must not make any assumptions about these `n` bytes.

This bug was introduced in https://github.com/CTSRD-CHERI/cheribsd/commit/92bb865938911e67dc4e98e73cd5239f62b31f76 .

**Comment by jrtc27** [comment]
Thanks for the report. @trasz do you know what you were trying to achieve back in 2018 with that commit?
