### ISSUE TITLE
Crash due to NULL capability with valid tag bit in basename

### ISSUE THREAD

**Issue by RichardsonAlex** [CTSRD-CHERI/cheribsd#218]
With the latest compiler (dev branch of llvm+clang+lld) and WITH_CHERI_PURE I am getting a permit load violation inside jemalloc when running basename.

```
(gdb) bt
#0  __je_tcache_alloc_small (arena=<optimized out>, size=<optimized out>, zero=<error reading variable: access outside bounds of object referenced via synthetic pointer>,
    slow_path=<error reading variable: access outside bounds of object referenced via synthetic pointer>, tsd=<optimized out>, tcache=<optimized out>, binind=<optimized out>)
    at /exports/users/alr48/sources/cheribsd-postmerge/contrib/jemalloc/include/jemalloc/internal/tcache.h:293
#1  __je_arena_malloc (tsdn=<optimized out>, size=<optimized out>, zero=<error reading variable: access outside bounds of object referenced via synthetic pointer>, tcache=<optimized out>,
    slow_path=<error reading variable: access outside bounds of object referenced via synthetic pointer>, arena=<optimized out>, ind=<optimized out>)
    at /exports/users/alr48/sources/cheribsd-postmerge/contrib/jemalloc/include/jemalloc/internal/arena.h:1356
#2  __je_iallocztm (size=<optimized out>, zero=<error reading variable: access outside bounds of object referenced via synthetic pointer>, tcache=<optimized out>,
    is_metadata=<error reading variable: access outside bounds of object referenced via synthetic pointer>, slow_path=<error reading variable: access outside bounds of object referenced via synthetic pointer>,
    tsdn=<optimized out>, ind=<optimized out>, arena=<optimized out>) at /exports/users/alr48/sources/cheribsd-postmerge/contrib/jemalloc/include/jemalloc/internal/jemalloc_internal.h:1092
#3  __je_ialloc (size=<optimized out>, zero=<error reading variable: access outside bounds of object referenced via synthetic pointer>,
    slow_path=<error reading variable: access outside bounds of object referenced via synthetic pointer>, tsd=<optimized out>, ind=<optimized out>)
    at /exports/users/alr48/sources/cheribsd-postmerge/contrib/jemalloc/include/jemalloc/internal/jemalloc_internal.h:1104
#4  ialloc_body (slow_path=<error reading variable: access outside bounds of object referenced via synthetic pointer>, size=<optimized out>, zero=<optimized out>, tsdn=<optimized out>, usize=<optimized out>)
    at jemalloc_jemalloc.c:1632
#5  __malloc (size=4096) at jemalloc_jemalloc.c:1671
#6  0x00000001200b7dd4 in __smakebuf (fp=<optimized out>) at /exports/users/alr48/sources/cheribsd-postmerge/lib/libc/stdio/makebuf.c:71
#7  0x00000001200b7c60 in __swsetup (fp=0x1200c8ac0 <__sF+768>) at /exports/users/alr48/sources/cheribsd-postmerge/lib/libc/stdio/wsetup.c:80
#8  0x00000001200b7150 in __sfvwrite (fp=0x7fffffdba8, uio=0x7fffffdf00) at /exports/users/alr48/sources/cheribsd-postmerge/lib/libc/stdio/fvwrite.c:64
#9  0x000000012009f89c in puts (s=<optimized out>) at /exports/users/alr48/sources/cheribsd-postmerge/lib/libc/stdio/puts.c:67
#10 0x0000000120010bc4 in main (argc=0, argv=0x7fffffe360) at /exports/users/alr48/sources/cheribsd-postmerge/usr.bin/basename/basename.c:110
```

The assembly is
```
   0x00000001200160d0 <+320>:   beqz    at,0x1200167a0 <__malloc+2064>
   0x00000001200160d4 <+324>:   nop
   0x00000001200160d8 <+328>:   sltiu   at,s0,14337
   0x00000001200160dc <+332>:   beqz    at,0x1200165c8 <__malloc+1592>
   0x00000001200160e0 <+336>:   nop
   0x00000001200160e4 <+340>:   dsll    v0,s4,0x6
=> 0x00000001200160e8 <+344>:   clw     v1,v0,112($c19)
   0x00000001200160ec <+348>:   daddiu  s0,v0,96
```

And the registers are
```
ddc: {attr = 0xffff00fa, cursor = 0x0, base = 0x0, length = 0x10000000000}
c1: {attr = 0xffff00fa, cursor = 0x120004800, base = 0x120004800, length = 0x728}
c2: {attr = 0xffff00fa, cursor = 0x418040, base = 0x0, length = 0x10000000000}
c3: {attr = 0xffff00fa, cursor = 0x7fffffdba8, base = 0x7fffffdba8, length = 0x78}
c4: {attr = 0xffff00fa, cursor = 0x7fffffdf00, base = 0x7fffffdf00, length = 0x40}
---Type <return> to continue, or q <return> to quit---
c5: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c6: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c7: {attr = 0xffff00fa, cursor = 0x1200e00a0, base = 0x1200e00a0, length = 0x20}
c8: {attr = 0xffff00fa, cursor = 0x1200e00c0, base = 0x1200e00c0, length = 0x4}
c9: {attr = 0xffff00fa, cursor = 0x1200e00e0, base = 0x1200e00e0, length = 0x20}
c10: {attr = 0xffff00fa, cursor = 0x7fffffda1c, base = 0x7fffffda1c, length = 0x1}
stc: {attr = 0xffff00fa, cursor = 0x7fff7ff000, base = 0x7fff7ff000, length = 0x7ff280}
c12: {attr = 0xfffd002e, cursor = 0x120015f90, base = 0x0, length = 0x10000000000}
c13: {attr = 0x100aa, cursor = 0x7fffffdee0, base = 0x7fffffdee0, length = 0x10}
c14: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c15: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c16: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c17: {attr = 0xfffd002e, cursor = 0x1200b7dd4, base = 0x0, length = 0x10000000000}
c18: {attr = 0xffff00fa, cursor = 0x1200c8ac0, base = 0x1200c87c0, length = 0x900}
c19: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c20: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c21: {attr = 0xffff00fa, cursor = 0x12000020a, base = 0x12000020a, length = 0x4}
c22: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c23: {attr = 0xffff00fa, cursor = 0x7fffffe360, base = 0x7fffffe320, length = 0x60}
c24: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
c25: {attr = 0x0, cursor = 0x0, base = 0x0, length = 0x0}
idc: {attr = 0xffff00fa, cursor = 0x0, base = 0x0, length = 0x10000000000}
```

Interestingly C19 has the tag bit set but is otherwise NULL.

If I make the following change to basename it no longer crashes:
```
diff --git a/usr.bin/basename/basename.c b/usr.bin/basename/basename.c
index fbb035035be..55bea871b95 100644
--- a/usr.bin/basename/basename.c
+++ b/usr.bin/basename/basename.c
@@ -62,12 +62,12 @@ main(int argc, char **argv)
        char *p, *suffix;
        size_t suffixlen;
        int aflag, ch;
-
+#if 0
        setlocale(LC_ALL, "");

        if (caph_limit_stdio() < 0 || (cap_enter() < 0 && errno != ENOSYS))
                err(1, "capsicum");
-
+#endif
        aflag = 0;
        suffix = NULL;
        suffixlen = 0;
```

I don't know yet which of the two function calls corrupts the jemalloc state.

**Comment by RichardsonAlex** [comment]
Seems like I was running this with a QEMU binary without https://github.com/CTSRD-CHERI/qemu/pull/43. Works fine now
